version: "2"

services:
  youtube-downloader-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VIRTUAL_HOST: youtube-downloader.quazarus.com
      VIRTUAL_PORT: 8080
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy